name: Sync Master to Develop
on:
  # Runs if a push is made to master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab, for testing purpose
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> develop
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: master
          target_branch: develop
          # custom token with admin access
          GITHUB_TOKEN: ${{ secrets.BRANCH_PROTECTION_OVERRIDE }}
