name: Tag and Sync post release
on:
  # Runs if a push is made to master branch
  push:
    branches: [ master ]
  # Allows manual running, for testing purposes
  workflow_dispatch:

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      version-tag: ${{ steps.version-tag.outputs.TAG }}
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Get merged branch
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        id: getMergedBranch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if merged pull request contained a tag
        uses: actions-ecosystem/action-regex-match@v2
        id: tag-regex
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '([0-9]\.[0-9](\.[0-9])?)'

      - name: Export tag content
        id: version-tag
        run: echo "::set-output name=TAG::${{ steps.tag-regex.outputs.match }}"

  tag-branch:
    needs: get-tag
    runs-on: ubuntu-latest
    # Only runs if tag was captured from regex
    if: ${{ needs.get-tag.outputs.version-tag}} != ""

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Tag master branch
        run: git tag "${{ needs.get-tag.outputs.version-tag }}"

      - name: Push tag to origin
        run: git push origin "${{ needs.get-tag.outputs.version-tag }}"

  sync-branches:
    needs: get-tag
    runs-on: ubuntu-latest
    # Only runs if tag was captured from regex
    if: ${{ needs.get-tag.outputs.version-tag}} != ""

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Merge master into develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          message: "Sync tag ${{ needs.get-tag.outputs.version-tag }} from master to develop"
          from_branch: master
          target_branch: develop
          # custom token with admin access
          github_token: ${{ secrets.BRANCH_PROTECTION_OVERRIDE }}