name: "Tag n' Sync"
on:
  # Runs if a push is made to master branch
  push:
    branches: [ master ]
  # Allows manual running, for testing purposes
  workflow_dispatch:

jobs:
  get-tag:
    outputs:
      hasTag: ${{ steps.hasTag.outputs.TAG }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
      - name: Get Merged Branch
      - id: getMergedBranch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if merged pull request contained a tag
      - id: hasTag
        run: echo "::set-output name=TAG::[[ ${{ github.event.commits[0].message }} =~ ^v[0-9]\.[0-9](\.[0-9])? && ${{ BASH_REMATCH[1] }} ]]"
  
  tag-branch:
    needs: get-tag
    # Only runs if tag was captured from regex
    if: [[ -z ${{ fromJSON(needs.get-tag.outputs.hasTag) }} ]]
    
    steps:
      tag-master:
        - uses: actions/checkout@v2
        - name: Tag master branch
          run: git tag "${{ fromJSON(needs.get-tag.outputs.hasTag) }}"
      
  sync-branches:
    needs: get-tag
    # Only runs if tag was captured from regex
    if: [[ -z ${{ fromJSON(needs.get-tag.outputs.hasTag) }} ]]
    
    steps:
      merge-master-to-develop:
      
        - uses: devmasx/merge-branch@master
          with:
            type: now
            message: "Sync develop with release ${{ fromJSON(needs.get-tag.outputs.hasTag) }}"
            from_branch: master
            target_branch: develop
            # custom token with admin access
            github_token: ${{ secrets.BRANCH_PROTECTION_OVERRIDE }}
